name: KIE assets plugin build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: "-Xmx4096m -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Generate all defined projects
        run: mvn clean --batch-mode --update-snapshots verify -pl kie-assets-plugin # use verify to run integration tests of maven plugin
      - name: Archive IT logs
        uses: actions/upload-artifact@v2
        if: always() && !cancelled()
        with:
          name: maven-plugin-IT
          path: kie-assets-plugin/target/it/*/build.log
