name: kn cli :: Generate Projects And Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: "-Xmx4096m -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: install kn cli
        uses: redhat-actions/openshift-tools-installer@v1`
        with:
          kn: "latest"
      - name: Install go-task
        uses: jaxxstorm/action-install-gh-release@v1.5.0
        with: # Grab the latest version
          repo: kiegroup/kie-tools
          platform: linux
          arch: x86-64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate all kn-cli defined projects
        run: mvn clean --batch-mode --update-snapshots package -Pkn-cli # use verify to run integration tests of maven plugin
      - name: Archive IT logs
        uses: actions/upload-artifact@v2
        if: always() && !cancelled()
        with:
          name: maven-plugin-IT
          path: kie-assets-plugin/target/it/*/build.log
      - name: Build generated projects
        run: for project in ./kie-assets-library-generate/target/*-grouping-project-pom.xml; do mvn clean package -f $project; done
