name: Quarkus CLI - Generate Projects And Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: "-Xmx4096m -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Generate all quarkus CLI defined projects
        run: mvn clean --batch-mode --update-snapshots package -Dactive.structures=quarkus-cli,quarkus-cli-with-registry -Dinstall.quarkus.cli
      - name: Build generated projects
        run: for project in ./kie-assets-library-generate/target/*-grouping-project-pom.xml; do mvn clean package -f $project; done
